
apiVersion: v1
data:
  password: changeme
kind: Secret
metadata:
  name: {{ .Values.pgClusterName }}-cert-keystore
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgClusterName }}-cert
spec:
  dnsNames:
  - {{ .Values.pgClusterName | trimSuffix "." }}
  - '*.{{ .Values.pgClusterName | trimSuffix "." }}'
  duration: {{ "43800h0m0s" }}
  commonName: {{ .Values.pgClusterName }}-cert
  secretName: {{ .Values.pgClusterName }}-cert
  privateKey:
    algorithm: ECDSA
    size: 256
{{- if .Values.TLS.ClusterIssuer }}
  issuerRef:
    name: {{ .Values.TLS.ClusterIssuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{ else }}
  issuerRef:
    name: {{ .Values.pgClusterName }}-root-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name:  {{ .Values.pgClusterName }}-cert-keystore
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: {{ .Values.pgClusterName }}-cert-keystore
---
