{{- if .Values.enableCloudBackup_AZ -}}
apiVersion: v1
kind: Secret
metadata:
  name: psql-backup-creds-{{ $.Values.pgClusterName }}
type: Opaque
stringData:
  AZURE_STORAGE_ACCESS_KEY: {{ $.Values.Clone.azureStorageAccessKey }}
  CLONE_AZURE_STORAGE_ACCESS_KEY: {{ $.Values.Clone.azureStorageAccessKey }}
{{- end -}}
