{{- if $.Values.isCommunity -}}
{{- range $pod := until ( .Values.numDataNodes | int) }}
---
apiVersion: v1
data:
  password: cG9zdGdyZXMxMjM=
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}
    team: {{ (split "-" $.Values.pgClusterName)._0 }}
  name: postgres.{{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}.credentials.postgresql.acid.zalan.do
type: Opaque
...
{{ end }}
{{ end }}
