{{- if $.Values.isCommunity -}}
{{- if $.Values.Vault.enabled }}
{{- range $pod := until ( .Values.numDataNodes | int) }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.pgClusterName | trunc 63 }}-data-{{ ($pod | toString) }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ $.Values.Vault.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: postgres.{{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}.credentials.postgresql.acid.zalan.do

    template:
      metadata:
        labels:
          application: spilo
          cluster-name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}
          team: {{ (split "-" $.Values.pgClusterName)._0 }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $.Values.Vault.vaultSecretPath }}
      property: {{ $.Values.Vault.adminUserNameKey }}
  - secretKey: password
    remoteRef:
      key: {{ $.Values.Vault.vaultSecretPath }}
      property: {{ $.Values.Vault.adminPasswordKey }}
---
{{ end }}
{{ end }}
{{ end }}
