apiVersion: v1
data:
  password: WTBjNWVtUkhaSGxhV0UwOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: {{ .Values.pgClusterName }}
    team: {{ (split "-" $.Values.pgClusterName)._0 }}
  name: postgres.{{ .Values.pgClusterName }}.credentials.postgresql.acid.zalan.do
type: Opaque
