{{- if $.Values.isCommunity -}}
{{- if $.Values.Monitor.enabled }}
{{- range $pod := until ( $.Values.numDataNodes | int) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}-{{ $.Values.Monitor.exporterServiceName }}
  labels:
    app: {{ $.Values.Monitor.exporterServiceName }}-data-{{ ($pod | toString) }}
    application: spilo
    team: {{ (split "-" $.Values.pgClusterName)._0 }}
    cluster-name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}
    release: {{ $.Release.Name }}
    Namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: {{ $.Values.Monitor.exporterServiceName }}-data-{{ ($pod | toString) }}
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    team: {{ (split "-" $.Values.pgClusterName)._0 }}
    cluster-name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}
---
{{- end }}
{{- end }}
{{- end }}
---
{{- if $.Values.isCommunity -}}
{{- if and ( $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( $.Values.Monitor.enabled ) }}
{{- range $pod := until ( $.Values.numDataNodes | int) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if $.Values.Monitor.labels }}
  labels:
{{ toYaml $.Values.Monitor.labels | indent 4}}
{{- end }}
  name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}-service-monitor
{{- if $.Values.Monitor.namespace }}
  namespace: {{ $.Values.Monitor.namespace }}
{{- end }}
spec:
  endpoints:
  - port: {{ $.Values.Monitor.exporterServiceName }}-data-{{ ($pod | toString) }}
{{- if $.Values.Monitor.interval }}
    interval: {{ $.Values.Monitor.interval }}
{{- end }}
{{- if $.Values.Monitor.telemetryPath }}
    path: {{ $.Values.Monitor.telemetryPath }}
{{- end }}
{{- if $.Values.Monitor.timeout }}
    scrapeTimeout: {{ $.Values.Monitor.timeout }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      application: spilo
      team: {{ (split "-" $.Values.pgClusterName)._0 }}
      cluster-name: {{ $.Values.pgClusterName }}-data-{{ ($pod | toString) }}
      release: {{ $.Release.Name }}
      app: {{ $.Values.Monitor.exporterServiceName }}-data-{{ ($pod | toString) }}
  targetLabels:
    - Namespace
    - release
---
{{- end }}
{{- end }}
{{- end }}
